### ISSUE TITLE
vvplot error

### ISSUE THREAD

**Issue by Tongyuanranseti** [vvflow/vvflow#22]
Thanks for the code. I just met a problem.
I am running it on wsl ubuntu 20.04. It went nornally at the very beginning, but when I was trying to vvplot the results, no visualized results occurred followed by such error:

vvplot results_re600_n350/000400.h5 bvs.png -x -2,18 -BVS
terminate called after throwing an instance of 'std::runtime_error'
  what():  Error running gnuplot: No such file or directory
make: *** [Makefile:17: bvs.png] Aborted
make: *** Deleting file 'bvs.png'

I have no idea how to fix it. Do you have any suggestions? (limited memory? etc.) Thanks~

**Comment by rosik** [comment]
You're missing gnuplot program installed

```
sudo apt install gnuplot
```
