### ISSUE TITLE
Vvflow custom bodies and motions

### ISSUE THREAD

**Issue by Scoulson986** [vvflow/vvflow#24]
Hi there, Thanks for your code. I'm new to vvflow and I have some questions.
1. Is there an option for custom bodies?I'm working on a fish simulation, and I found some build-in body generators such as gen_plate and gen_ellipse. They are quite useful but not accurate enough for the simulation. I would be very appreciated if there is an option for semi-ellipse.
2. How to drive the bodies? body:move_o(o) and body:move_d(d) seem to be the exact answer to rotate the body but I don't have any idea how to use it, and make the body move as the simulation time flows.
Thanks.

**Comment by rosik** [comment]
1. Take a look at `load_body()` function in vvcompose. Here's an exmple of square generation. 

```lua
#!/usr/bin/env vvcompose

S.inf_vx = "1"
S.re = 600
S.dt = 0.005
S.dt_save = 0.1
S.finish = 10

local f = assert(io.open("square.txt", "w"))

function w(x, y)
    f:write(string.format("%.2f %.2f\n", x, y))
end

local a = 1
local dl = 0.02
for y = 0, a, dl do w(0, y) end
for x = 0, a, dl do w(x, a) end
for y = a, 0, -dl do w(a, y) end
for x = a, 0, -dl do w(x, 0) end

f:close()

b0 = load_body("square.txt")
b0.label = "square"
S.body_list:insert(b0)

S.caption = "square_re600"
S:save(S.caption..".h5")
```  

![image](https://user-images.githubusercontent.com/2205188/213944613-da3f0de5-aae6-4aa7-b22e-7b0c10aff16e.png)

**Comment by rosik** [comment]
2. `body:move_*` is for initial adjustment. To define body motion during simulation see `body.holder_vx`. Supply it with a string - another lua script that returns a velocity. It can depend on variable `t`.

For example:

```lua
b0.holder_vy = "sin(2*pi*t/8)"
```

**Comment by Scoulson986** [comment]
Thanks！The example is really helpful. One more question about the body restrains. For multiple bodies like the fish simulation below, how to restain the freedom (eg: passive joints or hinges). is it possible to connect two bodies with passive joint in a custom position?

**Comment by Scoulson986** [comment]
> 2. `body:move_*` is for initial adjustment. To define body motion during simulation see `body.holder_vx`. Supply it with a string - another lua script that returns a velocity. It can depend on variable `t`.
> 
> For example:
> 
> ```lua
> b0.holder_vy = "sin(2*pi*t/8)"
> ```


Thanks！The example is really helpful. One more question about the body restrains. For multiple bodies like the fish simulation below, how to restain the freedom (eg: passive joints or hinges). is it possible to connect two bodies with passive joint in a custom position?

**Comment by rosik** [comment]
Excuse me for the late reply.

First of all, here's the link that might be helpful - [utils/vvcompose/vvcompose.1.md#TBody](https://github.com/vvflow/vvflow/blob/master/utils/vvcompose/vvcompose.1.md#tbody).

Vvflow models the bodies in the following way. Every body has an imaginary invisible holder (exactly one) with three degrees of freedom (designated as `x`, `y`, and `o` for rotation).  The holder can be either "ultimate", or attached to the other body (see `body.root`).  The holder also has a number of properties:
- coordinates `body.holder_pos`.
- disposition `body.delta_pos` if the connection is elastic.
- 
Also, `body.collision_min/max` constrain the value of `delta_pos`. When a body hits that constrain, it experiences a collision - a body gains additional momentum `- force_holder * (1 + body.bounce)` (`dt` is reduced implicitly).

And here's the setup of my old experiment - [flexyfoil.zip](https://github.com/vvflow/vvflow/files/10686340/flexyfoil.zip). I don't remember details already, but it should look something like this: https://www.youtube.com/watch?v=Tgguhu8G-PA&feature=youtu.be
