### ISSUE TITLE
Calculation of fluid force

### ISSUE THREAD

**Issue by Scoulson986** [vvflow/vvflow#26]
Hi there，I've build a fish mechanism based on your environment，it works pretty well but I want to get some specific data，such as the fluid resistance force. Is there a way to calculate it?
![image](https://user-images.githubusercontent.com/60203174/235308512-2d3d30f6-e391-4412-8f03-e831720f4c10.png)

Thank you.

**Comment by rosik** [comment]
Nice job!

I guess you need the sum of `force_hydro` across all bodies.

```bash
vvxtract stepdata.h5 time body00/force_hydro body01/force_hydro body02/force_hydro > force_hydro.txt
```

**Comment by Scoulson986** [comment]
I see. Btw the vvxtract command is really useful. I can get the friction force from the .h5 data as well.Thanks again for your reply and the efforts on this interesting program！
![微信截图_20230502103037](https://user-images.githubusercontent.com/60203174/235567085-ccdc220c-bde1-4058-b416-7a8b8a7351c4.png)
