### ISSUE TITLE
hello, I ran the sample files in ubuntu20.04 and 22.04 and did not have any problems with the calculations, but I kept getting errors processing the sample files(vvplot)

### ISSUE THREAD

**Issue by lss0523** [vvflow/vvflow#27]
#3 
terminate called after throwing an instance of 'std::runtime_error'
 what():  Error opening 'results_re600_n350/000150.h5': Failed to open 'results_re600_n350/000150.h5'

**Comment by rosik** [comment]
Looks like the experiment finished prematurely, before 150 step, so that file wasn't saved. Inspect what files are there with `ls results_re600_n350/` command.

**Comment by lss0523** [comment]
Thank you. My problem has been solved. I found the problem because I need 'sudo apt install gnuplot'.

**Comment by lss0523** [comment]
Excuse me, I want to know the definition of sports fish. Is it defined in the ".lua" file? I saw your animation of swimming fish on Yotube, it is really beautiful.

**Comment by rosik** [comment]
Here's the setup of my old experiment - https://github.com/vvflow/vvflow/files/10686340/flexyfoil.zip
