### ISSUE TITLE
Fail to build from Source

### ISSUE THREAD

**Issue by ConanoftheUnreal** [vvflow/vvflow#28]
Hi, I wanted to try vvflow on my computer, but came across a bunch of error messages when trying to build XStreamfunction.cpp.o. Here are the error messages that appeared during the process:

![image](https://github.com/vvflow/vvflow/assets/92651689/4c6796ed-842d-4428-8094-629222e6adbd)

This was a done on Archlinux.

**Comment by rosik** [comment]
What compiler and version do you use? Would you mind sharing full `cmake` output (in a clean build directory)?

P.S. It's fine for me on Ubuntu with GCC 11.

**Comment by ConanoftheUnreal** [comment]
I am using gcc 13.1.1 on Arch Linux and cmake version 3.26.3. The following is the output when I call cmake in a empty build directory:

Output from cmake:
-- The C compiler identification is GNU 13.1.1
-- The CXX compiler identification is GNU 13.1.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for sgemm_
-- Looking for sgemm_ - not found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Looking for sgemm_
-- Looking for sgemm_ - found
-- Found BLAS: /usr/lib/libblas.so  
-- Looking for cheev_
-- Looking for cheev_ - not found
-- Looking for cheev_
-- Looking for cheev_ - found
-- Found LAPACK: /usr/lib/liblapack.so;/usr/lib/libblas.so  
-- Adding CPack dependency for /usr/lib/liblapack.so
-- Adding CPack dependency for libgomp1
-- Extracted git-rev: 117c724adc59cb5179b7dfd877e5513410a74350
-- Extracted git-info: v2.2.2-1-g117c724
-- Extracted git-diff: 
-- Generating dpkg deps: libgomp1
-- Will put deb package to: deb
-- Configuring done (0.6s)
-- Generating done (0.0s)
-- Build files have been written to: /home/conar/Documents/vvflow/build

Result from ls:
![image](https://github.com/vvflow/vvflow/assets/92651689/1af818c7-762c-46b7-ae3f-bd30ba814c53)

**Comment by rosik** [comment]
Check out `v2.3.0` tag
